#include "application.h"

#include <swingby/cursor.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

enum wp_cursor_shape_device_v1_shape
_to_wp_cursor_shape(enum sb_cursor_shape shape)
{
    switch (shape) {
    case SB_CURSOR_SHAPE_DEFAULT:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_DEFAULT;
    case SB_CURSOR_SHAPE_CONTEXT_MENU:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_CONTEXT_MENU;
    case SB_CURSOR_SHAPE_HELP:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_HELP;
    case SB_CURSOR_SHAPE_POINTER:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_POINTER;
    case SB_CURSOR_SHAPE_PROGRESS:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_PROGRESS;
    case SB_CURSOR_SHAPE_WAIT:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_WAIT;
    case SB_CURSOR_SHAPE_CELL:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_CELL;
    case SB_CURSOR_SHAPE_CROSSHAIR:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_CROSSHAIR;
    case SB_CURSOR_SHAPE_TEXT:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_TEXT;
    case SB_CURSOR_SHAPE_VERTICAL_TEXT:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_VERTICAL_TEXT;
    case SB_CURSOR_SHAPE_ALIAS:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_ALIAS;
    case SB_CURSOR_SHAPE_COPY:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_COPY;
    case SB_CURSOR_SHAPE_MOVE:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_MOVE;
    case SB_CURSOR_SHAPE_NO_DROP:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NO_DROP;
    case SB_CURSOR_SHAPE_NOT_ALLOWED:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NOT_ALLOWED;
    case SB_CURSOR_SHAPE_GRAB:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_GRAB;
    case SB_CURSOR_SHAPE_GRABBING:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_GRABBING;
    case SB_CURSPR_SHAPE_E_RESIZE:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_E_RESIZE;
    case SB_CURSOR_SHAPE_N_RESIZE:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_N_RESIZE;
    case SB_CURSOR_SHAPE_NE_RESIZE:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NE_RESIZE;
    case SB_CURSOR_SHAPE_NW_RESIZE:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NW_RESIZE;
    case SB_CURSOR_SHAPE_S_RESIZE:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_S_RESIZE;
    case SB_CURSOR_SHAPE_SE_RESIZE:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_SE_RESIZE;
    case SB_CURSOR_SHAPE_SW_RESIZE:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_SW_RESIZE;
    case SB_CURSOR_SHAPE_W_RESIZE:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_W_RESIZE;
    case SB_CURSOR_SHAPE_EW_RESIZE:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_EW_RESIZE;
    case SB_CURSOR_SHAPE_NS_RESIZE:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NS_RESIZE;
    case SB_CURSOR_SHAPE_NESW_RESIZE:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NESW_RESIZE;
    case SB_CURSOR_SHAPE_NWSE_RESIZE:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NWSE_RESIZE;
    case SB_CURSOR_SHAPE_COL_RESIZE:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_COL_RESIZE;
    case SB_CURSOR_SHAPE_ROW_RESIZE:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_ROW_RESIZE;
    case SB_CURSOR_SHAPE_ALL_SCROLL:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_ALL_SCROLL;
    case SB_CURSOR_SHAPE_ZOOM_IN:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_ZOOM_IN;
    case SB_CURSOR_SHAPE_ZOOM_OUT:
        return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_ZOOM_OUT;
    default:
        break;
    }

    return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_DEFAULT;
}

#ifdef __cplusplus
}
#endif // __cplusplus
